### ISSUE TITLE
Expose tunnel status

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/wireguard_dart#10]
- [x] Streaming status updates (iOS/macOS) https://github.com/mysteriumnetwork/wireguard_dart/pull/36
- [x] Streaming status updates (Windows) https://github.com/mysteriumnetwork/wireguard_dart/pull/38
- [x] Streaming status updates (Android) https://github.com/mysteriumnetwork/wireguard_dart/pull/37

**Comment by dazevich** [comment]
When is implementation expected?

**Comment by tadaskay** [comment]
This/next week :)

> When is implementation expected?

**Comment by tadaskay** [comment]
Keeping this open: TODO windows status query and status streaming updates
