### ISSUE TITLE
"xxx" must be updated by the developer before "xxx" can be connected.

### ISSUE THREAD

**Issue by HiMsszhang** [mysteriumnetwork/wireguard_dart#46]
I refer to your example project to configure the android side normally, but the ios side reports an error："xxx" must be updated by the developer before "xxx" can be connected.
![IMG_0004](https://github.com/user-attachments/assets/be204594-3115-4c21-b3cd-17342892b74b)
Is there any configuration I'm missing?

**Comment by bbura** [comment]
@HiMsszhang did you manage to bypass this ?

**Comment by RomanPreis** [comment]
Same here, looking for a solution
